# This file is strictly for testing a base functionality of this chart
# it uses postgresql and valkey and provides credentials for them as well as mail

pixelfed:
  app:
    domain: "example.com"
  mail:
    username: test
    password: testing1234567
  horizon:
    separate_deployment: false
  pf:
    enable_cloud: true

valkey:
  auth:
    enabled: true
    password: testing1234567
  primary:
    replicaCount: 2
    disableCommands:
      - FLUSHALL
    persistence:
      enabled: false
  replica:
    replicaCount: 0
    persistence:
      enabled: false

postgresql:
  auth:
    password: testing1234567
    postgresPassword: testing1234567
    username: pixelfed
    database: pixelfed

minio:
  enabled: true
  provisioning:
    enabled: true
  persistence:
    enabled: false

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  httpGet:
    path: /api/service/health-check
    port: http

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  httpGet:
    path: /api/service/health-check
    port: http
