{{/*
Expand the name of the chart.
*/}}
{{- define "pixelfed.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "pixelfed.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "pixelfed.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "pixelfed.labels" -}}
helm.sh/chart: {{ include "pixelfed.chart" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "pixelfed.web.selectorLabels" -}}
app.kubernetes.io/name: {{ include "pixelfed.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/component: web
{{- end }}

{{/*
Horizon selector labels
*/}}
{{- define "pixelfed.horizon.selectorLabels" -}}
app.kubernetes.io/component: horizon
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "pixelfed.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "pixelfed.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Ensure minio password is set appropriately
*/}}
{{- if .Values.minio.enabled }}
    {{- if or (len (index .Values.minio.provisioning.users 0 "password") lt 8) (len (index .Values.minio.provisioning.users 0 "password") gt 40) }}
        {{- fail "pixelfed minio default user password not set. Set with --set minio.provisioning.users[0].password=..." }}
    {{- end }}
{{- end }}

{{/*
Helper variable to check if autogenerated minio cert are enabled.
*/}}
{{- define "pixelfed.minio.autogeneratedTls" -}}
{{- if and .Values.minio.tls.enabled .Values.minio.tls.autoGenerated }}
{{- true }}
{{- else }}
{{- false }}
{{- end }}
{{- end }}

{{/*
Merge extraInitContainers with any expected ones from the minio subchart.
*/}}
{{- define "pixelfed.mergedInitContainers" -}}
{{- $mergedInitContainers := .Values.extraInitContainers }}
{{- if (include "pixelfed.minio.autogeneratedTls" .) }}
{{- $mergedInitContainers = append $mergedInitContainers .Values.minio.tls.pixelfedInitContainer }}
{{- end }}
{{- toYaml $mergedInitContainers }}
{{- end }}

{{/*
Merge extraVolumes with any expected ones from the minio subchart.
*/}}
{{- define "pixelfed.mergedVolumes" -}}
{{- $mergedVolumes := .Values.extraVolumes }}
{{- if (include "pixelfed.minio.autogeneratedTls" .) }}
{{- $mergedVolumes = concat $mergedVolumes .Values.minio.tls.pixelfedVolumes }}
{{- end }}
{{- toYaml $mergedVolumes }}
{{- end }}

{{/*
Merge extraVolumeMounts with any expected ones from the minio subchart.
*/}}
{{- define "pixelfed.mergedVolumeMounts" -}}
{{- $mergedVolumeMounts := .Values.extraVolumeMounts }}
{{- if (include "pixelfed.minio.autogeneratedTls" .) }}
{{- $mergedVolumeMounts = concat $mergedVolumeMounts .Values.minio.tls.pixelfedVolumeMounts }}
{{- end }}
{{- toYaml $mergedVolumeMounts }}
{{- end }}