{{- if and (not .Values.pixelfed.s3.existingSecret) (and .Values.minio.enabled .Values.minio.provisioning.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pixelfed.fullname" . }}-s3
data:
  {{- if .Values.pixelfed.s3.url }}
  url: {{ .Values.pixelfed.s3.url | b64enc }}
  {{- else if and .Values.minio.enabled .Values.minio.provisioning.enabled }}
  url: {{ printf "https://%s:%v/%s" .Values.minio.fullnameOverride .Values.minio.service.ports.api (index .Values.minio.provisioning.buckets 0 "name") | b64enc }}
  {{- end }}

  {{- if .Values.pixelfed.s3.endpoint }}
  endpoint: {{ .Values.pixelfed.s3.endpoint | b64enc }}
  {{- else if and .Values.minio.enabled .Values.minio.provisioning.enabled }}
  endpoint: {{ printf "https://%s:%v" .Values.minio.fullnameOverride .Values.minio.service.ports.api | b64enc }}
  {{- end }}

  {{- if .Values.pixelfed.s3.bucket }}
  bucket: {{ .Values.pixelfed.s3.bucket | b64enc }}
  {{- else if and .Values.minio.enabled .Values.minio.provisioning.enabled }}
  bucket: {{ index .Values.minio.provisioning.buckets 0 "name" | b64enc }}
  {{- end }}

  {{- if .Values.pixelfed.s3.access_key_id }}
  access_key_id: {{ .Values.pixelfed.s3.access_key_id | b64enc }}
  {{- else if and .Values.minio.enabled .Values.minio.provisioning.enabled }}
  access_key_id: {{ index .Values.minio.provisioning.users 0 "username" | b64enc  }}
  {{- end }}

  {{- if .Values.pixelfed.s3.secret_access_key }}
  secret_access_key: {{ .Values.pixelfed.s3.secret_access_key | b64enc }}
  {{- else if and .Values.minio.enabled .Values.minio.provisioning.enabled }}
  secret_access_key: {{ index .Values.minio.provisioning.users 0 "password" | b64enc }}
  {{- end }}
{{- end }}
