{{- if not .Values.pixelfed.mail.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pixelfed-mail
data:
  host: {{ .Values.pixelfed.mail.host }}
  port: {{ .Values.pixelfed.mail.port }}
  {{- if .Values.pixelfed.mail.username }}
  username: {{ .Values.pixelfed.mail.username }}
  {{- end }}
  {{- if .Values.pixelfed.mail.password }}
  password: {{ .Values.pixelfed.mail.password }}
  {{- end }}
{{- end }}
